## 넘파이
- NumPy(Numerical Python) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- 정수나 실수와 같은 수치 데이터의 계산을 위해 사용한다.

#### 중요성
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있다.
- 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용한다.
- 판다스를 이해하는 데 많은 도움이 된다.

### ndarray 개요
- 넘파이의 기반 데이터 타입
- 넘파이에서 다차원(Multi-demension) 배열을 쉽게 생성하고 다양한 연산을 수행한다.

In [ ]:
#넘파이 모듈 임포트
import numpy as np # alias

- array() 함수 : 파이썬의 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환한다.
- ndarray 배열의 shape 변수 : ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있다. 이를 통해 배열의 차원까지 알 수 있다.

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태', array1.shape) #1차원 array로 3개의 데이터를 가지고 있다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태 (3,)


In [ ]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태', array2.shape) #2차원 array로 2개의 로우와 3개의 칼럼으로 구성되어 있다.

array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)


In [ ]:
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태', array3.shape) #2차원 array로 1개의 로우와 3개의 칼럼으로 구성되어 있다.

array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


- array1과 array3은 동일한 데이터 수를 가지고 있지만, array1은 명확하게 1차원임을 (3,)형태로 표현한 것이다.

In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- ndarray 배열의 ndim 변수 : ndarray의 차원
- 리스트 []는 1차원, 리스트의 리스트 [[]]는 2차원

### ndarray의 데이터 타입
- 숫자, 문자열, 불 값 등이 모두 가능하다.
- 숫자형의 경우 int, unsigned int, float형을 제공한다.
- 더 큰 숫자 값이나 정밀도를 위해 complex 타입을 제공한다.

In [ ]:
list1 = [1,2,3]
array1 = np.array(list1)
print(array1, array1.dtype)

[1 2 3] int32


- ndarray내의 데이터 타입은 dtype 속성으로 확인한다.

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


- astype() 메서드 : ndarray 내 데이터값의 타입 변경. 인자로 원하는 타입을 문자열로 지정한다.

In [ ]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int1 = array_float1.astype('int64')
print(array_int1, array_int1.dtype)

[1 2 3] int64


- float를 int형으로 변경할 때 소수점 이하는 당연히 모두 없어진다.

### ndarray를 편리하게 생성하기 - arange, zeros, ones
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 생성할 수 있다.
- 주로 테스트용 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용한다.

- arange() 함수 : 파이썬 표준 함수 range()와 유사한 기능을 한다. 0부터 함수 인자 값-1까지의 값을 순차적으로 ndarray의 데이터값으로 변환한다.

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.shape, sequence_array.dtype) #1차원 ndarray를 만든다.

[0 1 2 3 4 5 6 7 8 9]
(10,) int32


- zeros() 함수 : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다.
- ones() 함수 : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다.

In [ ]:
zero_array = np.zeros((3, 2), dtype='int64')
print(zero_array)
print(zero_array.shape, zero_array.dtype)

[[0 0]
 [0 0]
 [0 0]]
(3, 2) int64


In [ ]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.shape, one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2) float64


- 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다.

### ndarray의 차원과 크기를 변경하는 reshape()
- reshape() 메서드 : ndarray를 특정 차원 및 크기로 변환한다.
- 변환을 원하는 크기를 함수 인자로 부여한다.

In [ ]:
#0~9까지의 1차원 ndarray를 2*5 형태로 변환
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#array1.reshape(4,3)

- reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생한다.

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


- 인자로 -1을 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환한다.

In [ ]:
#array4 = array1.reshape(-1,4)

- 호환될 수 없는 형태는 -1을 사용하더라도 변환할 수 없다.

In [ ]:
#1차원 ndarray를 3차원 ndarray로 변환
array1 = np.arange(8)
array3d = array1.reshape(2, 2, 2)
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [ ]:
#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


In [ ]:
#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


- reshape(-1,1)을 이용해 3차원, 1차원을 2차원으로 변경한다.
- tolist() 메서드를 이용해 리스트로 자료형을 변환한다.

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출
2. 슬라이싱(Slicing)

#### 단일 값 추출
- 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1,10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [ ]:
value = array1[2]
print('value:', value)

value: 3


In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


- 단일 인덱스를 이용해 ndarray내의 데이터값을 수정할 수 있다.

In [ ]:
#다차원 ndarray에서 단일 값 추출
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(0,0) index 가리키는 값:', array2d[0,0])
print('(0,1) index 가리키는 값:', array2d[0,1])
print('(1,0) index 가리키는 값:', array2d[1,0])
print('(2,2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0,0) index 가리키는 값: 1
(0,1) index 가리키는 값: 2
(1,0) index 가리키는 값: 4
(2,2) index 가리키는 값: 9


#### 슬라이싱
- 슬라이싱은 연속된 인덱스상의 ndarray를 추출한다.

In [ ]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)

[1 2 3]


In [ ]:
print(type(array3))

<class 'numpy.ndarray'>


- 슬라이싱으로 추출된 데이터 세트는 모두 ndarray 타입이다.

In [ ]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [ ]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [ ]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원 ndarray에서 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2:\n',array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0:1]\n', array2d[0:2, 0:1])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0:1]
 [[1]
 [4]]


In [ ]:
print('array2d[:2, 0]\n', array2d[0:2, 0])
print('array2d[0, 0:2]\n', array2d[0, 0:2])
print('array2d[0:1, 0:2]\n', array2d[0:1, 0:2])

array2d[:2, 0]
 [1 4]
array2d[0, 0:2]
 [1 2]
array2d[0:1, 0:2]
 [[1 2]]


- 로우나 칼럼 축 한쪽에만 슬라이싱을 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용해도 된다.
- 한쪽에만 단일 값 인덱스를 적용하면 1차원 ndarray를 반환한다.

In [ ]:
print(array2d[0])
print(array2d[1])

[1 2 3]
[4 5 6]


- 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.